-- OFFLINE
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE,
       PRODUCT_ID, 
       Null USER_ID, -- USER_ID 컬럼을 NULL로 처리
       SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-03'

UNION ALL

-- ONLINE
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE,
       PRODUCT_ID, 
       USER_ID, 
       SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-03'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
