# SELECT A.ANIMAL_ID,
#        A.NAME,
#        DATEDIFF(B.DATETIME, A.DATETIME) AS 'PERIOD' 
# FROM ANIMAL_INS A JOIN ANIMAL_OUTS B
# ON A.ANIMAL_ID = B.ANIMAL_ID
# ORDER BY PERIOD DESC
# LIMIT 2;


SELECT A.ANIMAL_ID,
       A.NAME
FROM ANIMAL_INS A INNER JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY DATEDIFF(B.DATETIME, A.DATETIME) DESC
LIMIT 2;

