-- 생일이 3월인 여성 회원 조회
-- 전화번호가 NULL인 경우 제외
-- DATE_FORMAT() 날짜 출력 방식 수정

SELECT MEMBER_ID,
       MEMBER_NAME,
       GENDER,
       DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3
AND GENDER = "W"
AND TLNO IS NOT NULL;