# SUBSTRING(COLUMN , N, K) N번째 부터 K개
# A1 A2 C3 등으로 그룹화
# SELECT SUBSTRING(PRODUCT_CODE, 1, 2) AS CATEGORY_CODE,
#        COUNT(*) AS PRODUCTS
# FROM PRODUCT
# GROUP BY SUBSTRING(PRODUCT_CODE, 1, 2)
# ORDER BY CATEGORY_CODE;

# SELECT PRODUCT_CODE
# FROM PRODUCT
# WHERE SUBSTRING(PRODUCT_CODE, 1, 2) = 'A2' -- 3건

# SELECT PRODUCT_CODE
# FROM PRODUCT
# WHERE SUBSTRING(PRODUCT_CODE, 1, 2) = 'A3' -- 4건

SELECT SUBSTRING(PRODUCT_CODE, 1, 2) AS CATEGORY_CODE,
       COUNT(*)
FROM PRODUCT
GROUP BY SUBSTRING(PRODUCT_CODE, 1, 2)
ORDER BY CATEGORY_CODE;
